# Generated by Django 2.2.2 on 2020-08-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autho', '0002_auto_20200802_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(max_length=6, null=True, unique=True),
        ),
    ]
